### ISSUE TITLE
add named establishment generator

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#114]

**Comment by morgajel** [comment]
Look at the level of detail for tavern name generator... we'll need something similar (if not scaled back), for each type of establishment.

one thing the TavernGenerator doesn't do is potentially use the owner's name i.e. "Joe's Bar"

We may want to backport that feature to the TavernGenerator as we implement it in establishment generator.

**Comment by morgajel** [comment]
Created a baseline establishment based on tavern generator  still needs a lot of work.

**Comment by morgajel** [comment]
amenities need to be added.

**Comment by morgajel** [comment]
Fixed in 1dbb4cd762c67a621fc52827370a86f7c69175c4

This is complete
