### ISSUE TITLE
Abstract name generation out to a NameGenerator

### ISSUE THREAD

**Issue by morgajel** [CityGenerator/CityGenerator#123]
Pass in a parameter like Business, star, NPC, etc and any other requirements and it spits out a name.  May be a subroutine under GenericGenerator or a full Generator by itself, not sure yet.

**Comment by laanak08** [comment]
i feel like this one is already closed. Doesn't the NameGenerator code located here: https://github.com/CityGenerator/CityGenerator/blob/develop/namegenerator solve this problem?

**Comment by morgajel** [comment]
that is more of a pre-existing band-aid than a solution.  If you look at the implementation, it's calling TavernGenerator, WorldGenerator, etc and having to load/process each class. This issue is a move to consolidate them and potentially change the scope of parse_object as well.  If you look at each of the Generators, they have one (or more) name generation methods- worldGenerator for example has one for the world, moons and stars.

Make sense?

**Comment by laanak08** [comment]
If i understand your response correctly, you're saying, that the code for the name generation methods that are currently located within each class ( ie. WorldGenerator, TavernGenerator, etc...) should be abstracted out to the NameGenerator class so that it [ the NameGenerator class ] can generate them "natively"?

**Comment by morgajel** [comment]
yeah- the key part to understand is that the "namegenerator" script is more of a frontend, where as NameGenerator.pm would be a backend package in the lib dir.

**Comment by morgajel** [comment]
This has been refactored into Generator.py in megacosm.
