### ISSUE TITLE
Establishment text cleanup

### ISSUE THREAD

**Issue by morgajel** [CityGenerator/CityGenerator#148]
http://devcitygenerator.morgajel.net/?seed=707611#establishments

I've bolded suggestions inline...

The Lost Halfling is a smelly looking **,** normal sized translator facing southwest with a stone storefront, round windows, and a roof made from thatch **. It is located** in a rundown part of town **and is** run by a machiavellian male bugbear named Zhod Mokcrusher. This translator is known for varying prices for the service **there(get rid of there)** and holds the record for worst service in the region. There **are(is/are sucks)** 1 customers in the translator. The **mobsters taxes(plurality sucks)** the owner and patrons at the translator.

**Comment by braddoro** [comment]
Yeah I am not happy with the last sentence at all.  Sometimes they suck bad.

I also need to fix the 1 customers part.

did you add these astrics?  thatch**. It is located**

**Comment by morgajel** [comment]
yeah, I added it- it needed a preceding space to bold properly
