### ISSUE TITLE
add establishment trailer to name

### ISSUE THREAD

**Issue by morgajel** [CityGenerator/CityGenerator#150]
http://devcitygenerator.morgajel.net/?seed=707611#establishments

The Dripping Wench **Herbalist** is a dirty looking large sized herbalist shop facing north with a lap board storefront, large windows, and a roof made from slate in a seedy part of town run by a blinkered male deep dwarf named Brodal Pearlblood. This herbalist shop is known for fair prices for the service there and is usually empty. There are 5 customers in the herbalist shop. The grifters steals from the owner and patrons at the herbalist shop.

Make sure to capitalize it when you stick it to the name.

**Comment by braddoro** [comment]
I purposely left out the trailer because I did not like how the narrative was sounding with it.  The name was awkward in many places.  I have not rules it out, I just don't know how I want to implement it, or remove it.

The bug may be to remove the node from the xml or use it for something else.

**Comment by morgajel** [comment]
Can you give an example of one that doesnt work?

**Comment by braddoro** [comment]
Fixed
