### ISSUE TITLE
Military numbers are off from total population.

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#151]
http://devcitygenerator.morgajel.net/?seed=699197

Pop. Estimate: 37

Their standing army of 833 citizens (13.25%) is at the ready, with a reserve force of 345 (5.5%). Of the active duty military, 43 (5.25%) are special forces.

![selection_001](https://f.cloud.github.com/assets/2396396/961346/344d6aae-04d1-11e3-9b59-d87428b0e186.png)

**Comment by braddoro** [comment]
Oddly this one seems to work.

http://devcitygenerator.morgajel.net/?seed=707611

**Comment by morgajel** [comment]
keep in mind special forces is a percent of active military, not total population; is that where the confusion comes from?

**Comment by morgajel** [comment]
Was not passing population_total in, so it was just generating it on the fly.
