### ISSUE TITLE
Add collapsible divs around each establishment?

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#152]
Just a thought.

http://devcitygenerator.morgajel.net/?seed=707611#establishments

it is long text.  Maybe the DM wants to hide most establishments except for a few until they are discovered?

**Comment by morgajel** [comment]
I think re-organizing the layouts and collapsing the establishment test by default is a good idea, but for for a verbosity reduction sake; keep in mind this is a DM tool, so while the DM may give most of the info to the players, "hiding" it wouldn't be an effective tool for keeping players in the dark.

**Comment by morgajel** [comment]
complete as of c9a009f043f5a73f7a916e41aba9447edf0b372d
