### ISSUE TITLE
Pass in "available_races" to establishment to set the race of the manager

### ISSUE THREAD

**Issue by morgajel** [CityGenerator/CityGenerator#155]
the estabishment owners should reflect, roughly, the composition of the city. If it's a human and elf town, there shouldn't be 2 ogres and a mindflayer owning shops.

We can accomplish this by getting passing $city->{ 'available_races'} to the establishment generator, and then passing that to the NPCGenerator.

**Comment by braddoro** [comment]
nor should a serving wench be an amazon wizard.  unless she is working under cover to uncover a plot against her mentor when she was going through amazon wizard school.
