### ISSUE TITLE
Conflict Resolution scale

### ISSUE THREAD

**Issue by morgajel** [CityGenerator/CityGenerator#172]
fight vs talk (conflict resolution)

Lets come up with a list of phrases on the conflict resolution scale that can complete this sentence:

When Bob is confronted with conflict, he _________.
- won't raise a finger
- will try to talk it out
- will only resort to violence if no other option is available.
- will punch the conflict in the face.

Give me 10 more.

**Comment by Hyperaxie** [comment]
- will try to appeal to other people for help
- will stubbornly continue what he was doing in the first place.
- will yell a lot
- will make boasts and threats
  <-these are a few. not sure how good they are, but oh well

**Comment by morgajel** [comment]
moving this out of the 2.2 release to give @Hyperex more time to wor, on it.

**Comment by morgajel** [comment]
megacosm handles bravery and the NPC text specifically covers this.
