### ISSUE TITLE
Generate houses

### ISSUE THREAD

**Issue by morgajel** [CityGenerator/CityGenerator#18]
What do we want in a house?

Who is the head of household?
what is their race and profession?
What are their personality quirks and alignment?
if a business owner, is the business attached to the home?
how many children?
is their spouse alive? do any other family members live there?
how big is the house?
what is the quality of the house?
What rooms are there?
what possessions do they own?

**Comment by morgajel** [comment]
Also note this will contain the physical description of the house- construction, number of rooms, layout, basements, etc.

**Comment by braddoro** [comment]
Is this needed, how does this contribute to the game?

**Comment by morgajel** [comment]
As a DM, it's common for players to break into a house or otherwise need something similar. By having this information available via a separate generator, it adds flavor to the city. This would be most useful if it included generic/generated maps of some sort.

**Comment by morgajel** [comment]
Closed in favor of  https://github.com/CityGenerator/Megacosm-Generator/issues/36
