### ISSUE TITLE
Businesses and establishments do not match up.

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#180]
This is probably only an issue on very small cities.

http://devcitygenerator.morgajel.net/?seed=805060&size_roll=1

This says no business or specialists:

![selection_004](https://f.cloud.github.com/assets/2396396/1021683/ef4f62d8-0d1b-11e3-96fd-0d9e54e4d045.png)

We have this many named establishments:

![selection_005](https://f.cloud.github.com/assets/2396396/1021684/ffdeb72a-0d1b-11e3-9b84-c978d2e62789.png)

**Comment by morgajel** [comment]
will reimplement in megacosm.
