### ISSUE TITLE
Create a motive generator.

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#186]
something like:

When provoked Foo is likely to run 
When witnessing magic Foo is likely to run 
Foo is likely to respond favorably to a kind word or a bribe
Foo is generally interested in making some quick money with no questions asked.
Foo hates spiders
Foo likes unicorns

Maybe make a set of tolerances:
magic: 25
combat: 10
graft: 76
gullibility: 33
likes: long walks on the beach
dislikes: spiders, and mean people

Output:
Maybe make an expandable div so that when the NPC is met the DM can then expand the div and see the additional narrative.

this s related to issues:  https://github.com/CityGenerator/CityGenerator/issues/172 and  https://github.com/CityGenerator/CityGenerator/issues/43

**Comment by morgajel** [comment]
active in Megacosm Generator.
