### ISSUE TITLE
Add nodes for architectural styles

### ISSUE THREAD

**Issue by morgajel** [CityGenerator/CityGenerator#2]
What do the buildings look like? crude wooden huts? swiss or german homes? stone buildings? What building materials do they use?

**Comment by morgajel** [comment]
Resources to consider:
http://www.okhistory.org/shpo/106/archstyles.jpg
http://www.okhistory.org/shpo/106/archstyles1.jpg
http://en.wikipedia.org/wiki/Architectural_style
http://en.wikipedia.org/wiki/Medieval_architecture

**Comment by braddoro** [comment]
Is this important?  How does this contribute to the game?

**Comment by morgajel** [comment]
Another example of adding flavor to the game to help visualize it. I should merge this with ticket #18

**Comment by morgajel** [comment]
hah, to be clear, @braddoro meant attempt number 2, not issue number 2.  This guy still needs to be tacked via a #18 housing generator

**Comment by morgajel** [comment]
yes, @braddoro did finish this.
