### ISSUE TITLE
Switch everything to metric

### ISSUE THREAD

**Issue by morgajel** [CityGenerator/CityGenerator#35]
get rid of miles and yard in favor of kilometers and meters ( it makes calculations easier and less error-prone)

**Comment by braddoro** [comment]
heathen. :)  Maybe you should use some made up units which are just like metric so the metric lawyers don't come after you.  Ever since the lawsuit you can't be too careful.

**Comment by morgajel** [comment]
This has been cleaned out with the 2.x refactoring.
