### ISSUE TITLE
DungeonGenerator

### ISSUE THREAD

**Issue by morgajel** [CityGenerator/CityGenerator#80]
This is a big one... what needs to be generated for a dungeon?

**Comment by braddoro** [comment]
Would this dungeon maybe have a dragon in it?

**Comment by morgajel** [comment]
# What is needed here?

# Number of exits

# dimensions

# Number of floors

# Floor type

# Number of rooms

# Number of Doorways

**Comment by morgajel** [comment]
I have two good dungeon generators on megacosm now.
