### ISSUE TITLE
Can a brotha get a comma?

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#82]
http://citygenerator.morgajel.net/citygenerator?seed=792562

Census Data
General Information
Pop. Estimate: 48872
Children: 25.00% (12218)
Elderly: 1.50% (733)
Racial Breakdown
48383 ogre (98.9%)
489 other (1%)
Misc.
11 Districts
880 Businesses
7561 Specialists
5706 Residences

**Comment by morgajel** [comment]
This is intended to be a stat block; where does it need a comma?

**Comment by braddoro** [comment]
48872 as 48,872
48383 as 48,383
etc

**Comment by morgajel** [comment]
yeah, that's do-able. just need to figure out where in the formatters to add Number::Format

**Comment by morgajel** [comment]
completed for census data, summary and environment data. That should be everything for now.
