### ISSUE TITLE
Low amount of resources in smaller cities

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#85]
In my opinion I think I am seeing a too low amount of resources in smaller cities.  I think resource areas are great gaming points and there should be more.

Example city:
http://devcitygenerator.morgajel.net/citygenerator?seed=792534

**Comment by morgajel** [comment]
This is a good point; we can easily bump this up.

**Comment by morgajel** [comment]
current count is created in generate_resources which uses size_modifier and city economy. 

Poor economy will reduce the count, as well a small city.  Range is from 1-12... What range should we use, and how should these parameters be weighted?

**Comment by morgajel** [comment]
now will range from 5-22, depending on economy and size.
