### ISSUE TITLE
Tavern sentence structure

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#86]
Prices at the Randy Horse are dirt cheap and is owned by a dwarf named Garrim Quartzfighter who seems avuncular. 

Prices at the Elven Swagger are unreasonable and is owned by an orc named Kogoz Armbreaker who seems puckish.

These should read something iike:

The Elven Swagger is owned by a puckish orc named Kogoz Armbreaker and the prices are unreasonable.

Or 
The Elven Swagger is owned by a puckish orc named Kogoz Armbreaker.  The prices charged by Kogoz Armbreaker for his [wares] are unreasonable.

Maybe add a sentence that explains why people come to this bar.

**Comment by morgajel** [comment]
seems reasonable.

**Comment by morgajel** [comment]
fixed with #111
