### ISSUE TITLE
Remove basic+1 and monster+1 race combinations

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#88]
http://devcitygenerator.morgajel.net/citygenerator?seed=792494

Here's the breakdown of this basic+1 population:

**Comment by morgajel** [comment]
basic+1 is a remnant of the monstrous vs. basic population suggestions given by the DMG; I think it may be worth getting rid of completely in favor of monstrous, basic and mixed; basically 3 combinations instead of 5.

**Comment by morgajel** [comment]
Gone as of #126
