### ISSUE TITLE
Summary content displays population

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#90]
Upper Danvita is a large city in the Outer Moolgan District with a monstrous population of around 21429.

Does the population number belong here?

**Comment by morgajel** [comment]
The population number is there to give easy access to the size of the city. I'd like to replace this with a visual "city size scale" and flesh out this paragraph in other ways.

**Comment by morgajel** [comment]
ok, short term we should be able to peel off "of around x."

**Comment by morgajel** [comment]
fixed with 00eacee1777a8abbf91ce3ea8520f8ce2426ca1d
