### ISSUE TITLE
Racial content is duplicated

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#92]
Population

Races

Here's the breakdown of this random population:
48383 ogres (98.9%)
489 others (1%)

Racial Breakdown
19478 goblin (90.8%)
1778 ogre (8.2%)
173 other (0.8%)

I like this info in the census box.  I think the paragraph format can go away in favor of other content.

**Comment by morgajel** [comment]
agreed, this is redundant.

**Comment by morgajel** [comment]
Completed; removed via feature/issue#92... yeah, I know I used the flow incorrectly.
