### ISSUE TITLE
Business info is duplicated

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#93]
Buildings

There are 408 businesses in Upper Danvita and 2666 residences spread out across the city.

Misc.
5 Districts
408 Businesses
3269 Specialists
2666 Residences

I like this info in the census box.  I think the paragraph format can go away in favor of other content.

**Comment by morgajel** [comment]
yeah, this is redundant.

**Comment by morgajel** [comment]
Rather than removing it whole hog, what can we say about businesses in the city that could go here?

**Comment by morgajel** [comment]
Screw it- I removed the block from the formatter and the template.
