### ISSUE TITLE
Tavern sentence variable ANY

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#94]
Prices at the Chicken Silver are fair and is owned by an any named Joey Giacotone who seems beligerent. 

http://devcitygenerator.morgajel.net/citygenerator?seed=199999971

**Comment by morgajel** [comment]
any is a relic of saying any race is acceptable. I've worked around this by using the phrase "oddball" elsewhere. I need to find a better solution.

**Comment by morgajel** [comment]
Done enough for now. A hack is in place to fix this... needs to be revisited later.
