### ISSUE TITLE
provide interface for testing features/edge cases

### ISSUE THREAD

**Issue by morgajel** [CityGenerator/CityGenerator#95]
testing edge cases can be made easier by providing a simple web form to feed data in.

**Comment by braddoro** [comment]
Big Cities:
Libermead: 48872
http://devcitygenerator.morgajel.net/citygenerator?seed=792562
Jammer Keep: 56757
http://devcitygenerator.morgajel.net/citygenerator?seed=792531

Small Cities:
Galaesti: 27
http://devcitygenerator.morgajel.net/?seed=342747

Curlbert: 29
http://devcitygenerator.morgajel.net/citygenerator?seed=199999968

https://github.com/morgajel/CityGenerator.git

**Comment by morgajel** [comment]
new page is done. well, not done, but complete enough to use. Someone else can expand it if they want more features.

**Comment by morgajel** [comment]
For reference, it's /customcitygenerator
